language: python
jobs:
  include:
    - name: "Python 3.8.0 on Windows"
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: python py-solution/source/digit_recognition.py
